---
# The ZHA (Zigbee Home Automation) integration allows you to connect many
# off-the-shelf Zigbee based devices directly to Home Assistant, using one of
# the many available Zigbee coordinators.
#
# ZHA is configured via the UI. These are some advanced configuration option
# that are currently not available via the UI.
#
# https://www.home-assistant.io/integrations/zha
#
zha:
  zigpy_config:
    ota:
      ikea_provider: true
    network:
      channel: 25
      channels: [20, 25]
