---
# This automation turns off the ceiling light in our entrance
# as soon as there was no movement detected after 10 seconds.
#
# 10 seconds might seem short, but the sensor has a timeout of
# a minute as well. These 10 seconds gives it time to retrigger.
#
alias: hall_motion_lights_off
trigger:
  platform: state
  entity_id: binary_sensor.hall_motion
  to: 'off'
  for:
    seconds: 10
action:
  - service: switch.turn_off
    entity_id: switch.circadian_lighting_hall_circadian_lighting
  - service: light.turn_off
    data:
      entity_id: light.hall_ceiling
      transition: 15
