---
# This is for hiding Ikea Tradfri groups.
# Normally you would do this using setting an option on the Tradfri component
# but this functionality seems to be broken in the current release.
#
# https://github.com/home-assistant/home-assistant/issues/15084
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#
"light.tradfri_group_*":
  hidden: true
