---
custom_updater:
   track:
      - cards
      - components
      - python_scripts  
   card_urls:
      - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
      - https://raw.githubusercontent.com/ljmerza/calendar-card/master/custom_updater.json
      - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
      - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
      