---
#
# The restart switch platform allows you to restart your node remotely through
# Home Assistant.
#
# I wish there was a single service for this, by default...
#
# https://esphome.io/components/switch/restart.html
#
platform: restart
id: switch_restart
name: "${name} Restart"
