---
# This alerts me on my iPhone when a new release
# of Home Assistant for Hass.io is released.
#
alias: system_upgrade_alert
trigger:
  platform: state
  entity_id: sensor.version_available
condition:
  - condition: template
    value_template: >-
      {{
        states('sensor.version_available')
        !=
        states('sensor.version_current')
      }}
action:
  - service: notify.ios_francks_iphone
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      data:
        attachment:
          content-type: png
          url: https://png2.kisspng.com/20180504/avq/kisspng-computer-icons-starburst-clip-art-the-store-to-upgrade-kuangshuai-5aecf79d6760f6.2104595515254793254235.png
  - service: persistent_notification.create
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      notification_id: hassio_upgrade
