---
alias: Living Room Lights On
description: >-
  Turn living room lights on.

  Turn on the lights on the living room based on a couple of factors. Mainly
  the outside luminosity matters. This turns on lights when there is not
  enough light outside.

  Also, the entrance door to our living room has a sensor. If entering the room
  in the night, the lights will turn on.

id: 7b5d4cf0-7129-4486-89a9-4216d2d2e12a
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.living_room_door
      - input_boolean.living_room_automatic_lighting
      - sensor.garden_luminosity

condition:
  - condition: state
    entity_id:
      - input_boolean.living_room_automatic_lighting
    state: "on"
  - condition: numeric_state
    entity_id:
      - sensor.garden_luminosity
    below: 450.0
  - condition: or
    conditions:
      - condition: state
        entity_id:
          - alarm_control_panel.home_alarm
        state: disarmed
      - condition: state
        entity_id:
          - binary_sensor.living_room_door
        state: "on"

action:
  - service: light.turn_on
    target:
      area_id: living_room
    data:
      transition: 3
