---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * *"

permissions: {}

jobs:
  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@941d5d917f4c1c7a7e7d4087526daf90d53f4437 # v1.4
        with:
          path: "."
          secrets: ./secrets.fake.yaml
          version: "${{ matrix.version }}"
